// Converts old_database CSV exports to a Supabase seed migration SQL file.
// Run: node scripts/generate_seed.mjs
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, '..');
const CSV_DIR = join(ROOT, 'old_database');
const OUT = join(ROOT, 'supabase', 'migrations', '20240103000000_seed_old_data.sql');

function parseCSV(content) {
  const lines = content.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n');
  const headers = lines[0].split(';');
  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    if (!lines[i].trim()) continue;
    // Split on semicolons but handle quoted fields
    const values = splitCSVLine(lines[i]);
    if (values.length !== headers.length) continue;
    const row = {};
    headers.forEach((h, idx) => { row[h] = values[idx]; });
    rows.push(row);
  }
  return { headers, rows };
}

function splitCSVLine(line) {
  const values = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') { current += '"'; i++; }
      else { inQuotes = !inQuotes; }
    } else if (ch === ';' && !inQuotes) {
      values.push(current);
      current = '';
    } else {
      current += ch;
    }
  }
  values.push(current);
  return values;
}

function sqlVal(v) {
  if (v === '' || v === null || v === undefined) return 'NULL';
  if (v === 'true') return 'true';
  if (v === 'false') return 'false';
  // Escape single quotes
  return `'${v.replace(/'/g, "''")}'`;
}

function insertBlock(table, headers, rows, conflictAction = 'DO NOTHING') {
  if (rows.length === 0) return `-- ${table}: no rows\n`;
  const cols = headers.join(', ');
  const valueLines = rows.map(row =>
    `  (${headers.map(h => sqlVal(row[h])).join(', ')})`
  );
  const chunks = [];
  // Split into chunks of 500 rows to avoid huge single statements
  const CHUNK = 500;
  for (let i = 0; i < valueLines.length; i += CHUNK) {
    const slice = valueLines.slice(i, i + CHUNK);
    chunks.push(
      `INSERT INTO public.${table} (${cols}) VALUES\n${slice.join(',\n')}\nON CONFLICT (id) ${conflictAction};`
    );
  }
  return chunks.join('\n\n');
}

function readCSV(prefix) {
  const files = readdirSync(CSV_DIR);
  const file = files.find(f => f.startsWith(prefix + '-export'));
  if (!file) throw new Error(`CSV not found for: ${prefix}`);
  return parseCSV(readFileSync(join(CSV_DIR, file), 'utf8'));
}

// Need readdirSync
import { readdirSync } from 'fs';

const TABLES = [
  'challenge_types',
  'bars',
  'profiles',
  'performances',
  'performance_yermats',
  'performance_comments',
  'bar_follows',
  'user_follows',
  'monthly_medals',
  'notifications',
  'user_roles',
  'tiktok_consents',
];

// Tables to skip
const SKIP = new Set(['push_subscriptions', 'bar_rewards']);

const parts = [];

parts.push(`-- Seed migration: import from old fizzy-walrus database (exported 2026-05-18)
-- Generated by scripts/generate_seed.mjs
-- DO NOT EDIT MANUALLY

SET session_replication_role = replica; -- disable FK triggers during bulk import
`);

// challenge_types: delete existing seeded rows (different UUIDs) then re-insert
{
  const { headers, rows } = readCSV('challenge_types');
  parts.push(`-- challenge_types: replace seeded rows (UUID mismatch with old data)
DELETE FROM public.challenge_types;
${insertBlock('challenge_types', headers, rows)}
`);
}

// All other tables in order (challenge_types already done)
for (const table of TABLES.slice(1)) {
  const { headers, rows } = readCSV(table);
  parts.push(`-- ${table}: ${rows.length} rows
${insertBlock(table, headers, rows)}
`);
}

parts.push(`SET session_replication_role = DEFAULT;
`);

const sql = parts.join('\n');
writeFileSync(OUT, sql, 'utf8');
console.log(`✓ Written to ${OUT}`);
console.log(`  Total size: ${(sql.length / 1024).toFixed(1)} KB`);
